my_list=[1,2,3,4,5,6,4,4,3,3]
my_list.append(9999)
print(*my_list)
my_list.insert(2,45)
print(*my_list)
my_list.pop(4)
print(*my_list)
print(len(my_list))
my_list_2=[5,8,9,7,6]
new_list=my_list+my_list_2
print(*new_list)
new_list=my_list.copy()
new_list.pop(2)
print(*new_list)
count=my_list.count(3)
print(count)
my_list.sort()
print(*my_list)